# Основная конфигурация приложения (активна по умолчанию)
server:
  # Порт, на котором будет запущено приложение
  port: 8090

spring:
  application:
    # Имя приложения для идентификации в сервисе Discovery (Eureka и т.д.)
    name: rococo-gateway

  # Конфигурация безопасности
  security:
    oauth2:
      resourceserver:
        jwt:
          # URL сервера авторизации (OAuth2) для проверки JWT токенов
          issuer-uri: 'http://127.0.0.1:9000'

# Настройки логирования
logging:
  level:
    root: ERROR   # Базовый уровень логирования
    # Детальное логирование для Spring компонентов
    org.springframework.web: ERROR
    org.springframework.security: ERROR
    org.springframework.security.oauth2: ERROR
    org.springframework.boot.autoconfigure: ERROR
  file:
    path: ./logs/rococo-gateway

# Кастомные настройки приложения
rococo-userdata:
  client: rest  # Использование REST клиента для сервиса userdata

rococo-front:
  base-uri: 'http://127.0.0.1:3000'  # Базовый URL фронтенд-приложения

---
# Конфигурация для профиля "local"
spring:
  config:
    activate:
      on-profile: 'local'  # Активация настроек только для профиля "local"

  # Отключение автоконфигурации Vault (не используется в локальном окружении)
  autoconfigure:
    exclude:
      - 'org.springframework.cloud.vault.config.VaultAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultObservationAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultReactiveAutoConfiguration'

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://127.0.0.1:9000'  # Локальный сервер авторизации

# URL микросервисов в локальном окружении
rococo-userdata:
  base-uri: 'http://127.0.0.1:8285'
rococo-front:
  base-uri: 'http://127.0.0.1:3000'
rococo-artist:
  base-uri: 'http://127.0.0.1:8282'
rococo-museum:
  base-uri: 'http://127.0.0.1:8283'
rococo-painting:
  base-uri: 'http://127.0.0.1:8284'
rococo-gateway:
  base-uri: 'http://127.0.0.1:8090'

---
# Конфигурация для профиля "docker"
spring:
  config:
    activate:
      on-profile: 'docker'  # Активация настроек только для профиля "docker"

  # Отключение автоконфигурации Vault
  autoconfigure:
    exclude:
      - 'org.springframework.cloud.vault.config.VaultAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultObservationAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultReactiveAutoConfiguration'

  security:
    oauth2:
      resourceserver:
        jwt:
          # Сервер авторизации в Docker-сети
          issuer-uri: 'http://auth.rococo.dc:9000'

# URL микросервисов в Docker окружении (сервисы в отдельных контейнерах)
rococo-userdata:
  base-uri: 'http://userdata.rococo.dc:8285'
rococo-front:
  base-uri: 'http://frontend.rococo.dc'
rococo-artist:
  base-uri: 'http://artist.rococo.dc:8282'
rococo-museum:
  base-uri: 'http://museum.rococo.dc:8283'
rococo-painting:
  base-uri: 'http://painting.rococo.dc:8284'
rococo-gateway:
  base-uri: 'http://gateway.rococo.dc:8090'