package guru.qa.rococo.model.rest.museum;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.ToString;

import java.util.concurrent.ThreadLocalRandom;

@AllArgsConstructor
@Getter
@ToString
public enum Country {
  AUSTRALIA("Австралия"),
  AUSTRIA("Австрия"),
  AZERBAIJAN("Азербайджан"),
  ALBANIA("Албания"),
  ALGERIA("Алжир"),
  ANGOLA("Ангола"),
  ANDORRA("Андорра"),
  ANTIGUA_AND_BARBUDA("Антигуа и Барбуда"),
  ARGENTINA("Аргентина"),
  ARMENIA("Армения"),
  AFGHANISTAN("Афганистан"),
  BAHAMAS("Багамские Острова"),
  BANGLADESH("Бангладеш"),
  BARBADOS("Барбадос"),
  BAHRAIN("Бахрейн"),
  BELIZE("Белиз"),
  BELARUS("Белоруссия"),
  BELGIUM("Бельгия"),
  BENIN("Бенин"),
  BULGARIA("Болгария"),
  BOLIVIA("Боливия"),
  BOSNIA_AND_HERZEGOVINA("Босния и Герцеговина"),
  BOTSWANA("Ботсвана"),
  BRAZIL("Бразилия"),
  BRUNEI("Бруней"),
  BURKINA_FASO("Буркина-Фасо"),
  BURUNDI("Бурунди"),
  BHUTAN("Бутан"),
  VANUATU("Вануату"),
  UNITED_KINGDOM("Великобритания"),
  HUNGARY("Венгрия"),
  VENEZUELA("Венесуэла"),
  EAST_TIMOR("Восточный Тимор"),
  VIETNAM("Вьетнам"),
  GABON("Габон"),
  HAITI("Республика Гаити"),
  GUYANA("Гайана"),
  GAMBIA("Гамбия"),
  GHANA("Гана"),
  GUATEMALA("Гватемала"),
  GUINEA("Гвинея"),
  GUINEA_BISSAU("Гвинея-Бисау"),
  GERMANY("Германия"),
  HONDURAS("Гондурас"),
  GRENADA("Гренада"),
  GREECE("Греция"),
  GEORGIA("Грузия"),
  DENMARK("Дания"),
  DJIBOUTI("Джибути"),
  DOMINICA("Доминика"),
  DOMINICAN_REPUBLIC("Доминиканская Республика"),
  EGYPT("Египет"),
  ZAMBIA("Замбия"),
  ZIMBABWE("Зимбабве"),
  ISRAEL("Израиль"),
  INDIA("Индия"),
  INDONESIA("Индонезия"),
  JORDAN("Иордания"),
  IRAQ("Ирак"),
  IRAN("Иран"),
  IRELAND("Ирландия"),
  ICELAND("Исландия"),
  SPAIN("Испания"),
  ITALY("Италия"),
  YEMEN("Йемен"),
  CABO_VERDE("Кабо-Верде"),
  KAZAKHSTAN("Казахстан"),
  CAMBODIA("Камбоджа"),
  CAMEROON("Камерун"),
  CANADA("Канада"),
  QATAR("Катар"),
  KENYA("Кения"),
  CYPRUS("Республика Кипр"),
  KYRGYZSTAN("Киргизия"),
  KIRIBATI("Кирибати"),
  CHINA("Китай"),
  COLOMBIA("Колумбия"),
  COMOROS("Коморы"),
  CONGO_REPUBLIC("Республика Конго"),
  CONGO_DEMOCRATIC_REPUBLIC("Демократическая Республика Конго"),
  NORTH_KOREA("Корейская Народно-Демократическая Республика"),
  SOUTH_KOREA("Республика Корея"),
  COSTA_RICA("Коста-Рика"),
  IVORY_COAST("Кот-д’Ивуар"),
  CUBA("Куба"),
  KUWAIT("Кувейт"),
  LAOS("Лаос"),
  LATVIA("Латвия"),
  LESOTHO("Лесото"),
  LIBERIA("Либерия"),
  LEBANON("Ливан"),
  LIBYA("Ливия"),
  LITHUANIA("Литва"),
  LIECHTENSTEIN("Лихтенштейн"),
  LUXEMBOURG("Люксембург"),
  MAURITIUS("Маврикий"),
  MAURITANIA("Мавритания"),
  MADAGASCAR("Мадагаскар"),
  MALAWI("Малави"),
  MALAYSIA("Малайзия"),
  MALI("Мали"),
  MALDIVES("Мальдивы"),
  MALTA("Мальта"),
  MOROCCO("Марокко"),
  MARSHALL_ISLANDS("Маршалловы Острова"),
  MEXICO("Мексика"),
  MICRONESIA("Федеративные Штаты Микронезии"),
  MOZAMBIQUE("Мозамбик"),
  MOLDOVA("Молдавия"),
  MONACO("Монако"),
  MONGOLIA("Монголия"),
  MYANMAR("Мьянма"),
  NAMIBIA("Намибия"),
  NAURU("Науру"),
  NEPAL("Непал"),
  NIGER("Нигер"),
  NIGERIA("Нигерия"),
  NETHERLANDS("Нидерланды"),
  NICARAGUA("Никарагуа"),
  NEW_ZEALAND("Новая Зеландия"),
  NORWAY("Норвегия"),
  UAE("Объединённые Арабские Эмираты"),
  OMAN("Оман"),
  PAKISTAN("Пакистан"),
  PALAU("Палау"),
  PANAMA("Панама"),
  PAPUA_NEW_GUINEA("Папуа — Новая Гвинея"),
  PARAGUAY("Парагвай"),
  PERU("Перу"),
  POLAND("Польша"),
  PORTUGAL("Португалия"),
  RUSSIA("Россия"),
  RWANDA("Руанда"),
  ROMANIA("Румыния"),
  EL_SALVADOR("Сальвадор"),
  SAMOA("Самоа"),
  SAN_MARINO("Сан-Марино"),
  SAO_TOME_AND_PRINCIPE("Сан-Томе и Принсипи"),
  SAUDI_ARABIA("Саудовская Аравия"),
  NORTH_MACEDONIA("Флаг Северной Македонии"),
  SEYCHELLES("Сейшельские Острова"),
  SENEGAL("Сенегал"),
  SAINT_VINCENT_AND_GRENADINES("Сент-Винсент и Гренадины"),
  SAINT_KITTS_AND_NEVIS("Сент-Китс и Невис"),
  SAINT_LUCIA("Сент-Люсия"),
  SERBIA("Сербия"),
  SINGAPORE("Сингапур"),
  SYRIA("Сирия"),
  SLOVAKIA("Словакия"),
  SLOVENIA("Словения"),
  USA("Соединённые Штаты Америки"),
  SOLOMON_ISLANDS("Соломоновы Острова"),
  SOMALIA("Сомали"),
  SUDAN("Судан"),
  SURINAME("Суринам"),
  SIERRA_LEONE("Сьерра-Леоне"),
  TAJIKISTAN("Таджикистан"),
  THAILAND("Таиланд"),
  TANZANIA("Танзания"),
  TOGO("Того"),
  TONGA("Тонга"),
  TRINIDAD_AND_TOBAGO("Тринидад и Тобаго"),
  TUVALU("Тувалу"),
  TUNISIA("Тунис"),
  TURKMENISTAN("Туркменистан"),
  TURKEY("Турция"),
  UGANDA("Уганда"),
  UZBEKISTAN("Узбекистан"),
  UKRAINE("Украина"),
  URUGUAY("Уругвай"),
  FIJI("Фиджи"),
  PHILIPPINES("Филиппины"),
  FINLAND("Финляндия"),
  FRANCE("Франция"),
  CROATIA("Хорватия"),
  CENTRAL_AFRICAN_REPUBLIC("Центральноафриканская Республика"),
  CHAD("Чад"),
  MONTENEGRO("Черногория"),
  CZECHIA("Чехия"),
  CHILE("Чили"),
  SWITZERLAND("Швейцария"),
  SWEDEN("Швеция"),
  SRI_LANKA("Шри-Ланка"),
  ECUADOR("Эквадор"),
  EQUATORIAL_GUINEA("Экваториальная Гвинея"),
  ERITREA("Эритрея"),
  ESWATINI("Эсватини"),
  ESTONIA("Эстония"),
  ETHIOPIA("Эфиопия"),
  SOUTH_AFRICA("Южно-Африканская Республика"),
  SOUTH_SUDAN("Южный Судан"),
  JAMAICA("Ямайка"),
  JAPAN("Япония"),
  VATICAN("Ватикан"),
  PALESTINE("Палестина");

  private final String country;

  public static Country random() {
    Country[] values = values();
    int idx = ThreadLocalRandom.current().nextInt(values.length);
    return values[idx];
  }
}
